name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Install dependencies
      run: dotnet restore ./src/testapi.sln
    - name: Build
      run: dotnet build ./src/testapi.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ./src/testapi.sln --no-restore --verbosity normal --filter TestCatgeory=Unit
